### ISSUE TITLE
What does this do ?

### ISSUE THREAD

**Issue by stuaxo** [atuchak/pytest-django-cache-xdist#1]
Does this clear djangos cached_properties, something else ?

It would be good if there was a sentence or two describing what this does with the django cache when running in pytest and how to use it from pytest.

**Comment by atuchak** [comment]
@stuaxo 

how to use it from pytest?
This plugin automatically set pytest fixture up. 

what this does with the django cache when running in pytest?
It setups a unique django cache prefix for each xdist process.

Does this clear djangos cached_properties, something else ?
No, it does not. The only thing this fixture do is providing thread safety by using a unique django cache prefix for each xdist process.

**Comment by stuaxo** [comment]
Thanks :) think I was a bit blinded by the task I was trying to solve, this is quite a useful project.

**Comment by stuaxo** [comment]
I put your answers into a small PR #2

**Comment by atuchak** [comment]
@stuaxo Thanks
